const {
    getNextUrlId,
    findUrlByShortCode,
    findActiveUrlByShortCode,
    createUrlRecord,
    listAllShortCodes
} = require("../models/url.model");
const { encodeBase62 } = require("../utils/base62");
const HttpError = require("../utils/http-error");
const logger = require("../config/logger");
const { redis, getRedisCacheTtlSeconds } = require("../config/redis");
const {
    initializeShortCodeFilter,
    isShortCodeFilterReady,
    mightContainShortCode,
    addShortCode
} = require("./short-code-filter.service");

const CUSTOM_ALIAS_REGEX = /^[a-zA-Z0-9_-]{3,64}$/;
const REDIRECT_CACHE_PREFIX = "redirect:";

function getRedirectCacheKey(shortCode) {
    return `${REDIRECT_CACHE_PREFIX}${shortCode}`;
}

function isExpired(expiryAt) {
    return expiryAt ? new Date(expiryAt).getTime() <= Date.now() : false;
}

function assertValidUrl(url) {
    if (!url || typeof url !== "string") {
        throw new HttpError(400, "'url' is required and must be a string");
    }

    let parsed;

    try {
        parsed = new URL(url);
    } catch {
        throw new HttpError(400, "'url' must be a valid absolute URL");
    }

    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
        throw new HttpError(400, "'url' must start with http:// or https://");
    }

    return parsed.toString();
}

function parseExpiry(expiry) {
    if (expiry === undefined || expiry === null || expiry === "") {
        return null;
    }

    const parsedDate = new Date(expiry);

    if (Number.isNaN(parsedDate.getTime())) {
        throw new HttpError(400, "'expiry' must be a valid date/time");
    }

    if (parsedDate <= new Date()) {
        throw new HttpError(400, "'expiry' must be a future date/time");
    }

    return parsedDate;
}

function assertValidCustomAlias(customAlias) {
    if (customAlias === undefined || customAlias === null || customAlias === "") {
        return null;
    }

    if (typeof customAlias !== "string") {
        throw new HttpError(400, "'customAlias' must be a string when provided");
    }

    if (!CUSTOM_ALIAS_REGEX.test(customAlias)) {
        throw new HttpError(
            400,
            "'customAlias' must be 3-64 chars using letters, numbers, '-' or '_'"
        );
    }

    return customAlias;
}

async function reserveAutoGeneratedCode(originalUrl, expiryAt) {
    const maxAttempts = 8;

    for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
        const id = await getNextUrlId();
        const shortCode = encodeBase62(id);

        try {
            return await createUrlRecord({ id, originalUrl, shortCode, expiryAt });
        } catch (error) {
            if (error.code !== "23505") {
                throw error;
            }
        }
    }

    throw new HttpError(503, "Unable to generate a unique short code right now");
}

async function createShortUrl(payload) {
    const originalUrl = assertValidUrl(payload?.url);
    const customAlias = assertValidCustomAlias(payload?.customAlias);
    const expiryAt = parseExpiry(payload?.expiry);

    if (customAlias) {
        const existing = await findUrlByShortCode(customAlias);
        if (existing) {
            throw new HttpError(409, "customAlias already exists");
        }

        try {
            const id = await getNextUrlId();
            const created = await createUrlRecord({
                id,
                originalUrl,
                shortCode: customAlias,
                expiryAt
            });

            addShortCode(created.short_code);
            return created;
        } catch (error) {
            if (error.code === "23505") {
                throw new HttpError(409, "customAlias already exists");
            }

            throw error;
        }
    }

    const created = await reserveAutoGeneratedCode(originalUrl, expiryAt);
    addShortCode(created.short_code);
    return created;
}

async function resolveRedirectTarget(shortCode) {
    if (!shortCode || typeof shortCode !== "string") {
        throw new HttpError(400, "shortCode is required");
    }

    const normalizedShortCode = shortCode.trim();

    if (!normalizedShortCode) {
        throw new HttpError(400, "shortCode is required");
    }

    if (isShortCodeFilterReady() && !mightContainShortCode(normalizedShortCode)) {
        logger.info({ shortCode: normalizedShortCode }, "Bloom filter rejected unknown short code");
        throw new HttpError(404, "Short URL not found");
    }

    const cacheKey = getRedirectCacheKey(normalizedShortCode);

    try {
        const cachedUrl = await redis.get(cacheKey);

        if (cachedUrl) {
            logger.info({ shortCode: normalizedShortCode, cacheKey }, "Redirect cache hit");

            return {
                originalUrl: cachedUrl,
                source: "cache"
            };
        }

        logger.info({ shortCode: normalizedShortCode, cacheKey }, "Redirect cache miss");
    } catch (error) {
        logger.warn({ err: error, shortCode: normalizedShortCode, cacheKey }, "Redirect cache lookup failed");
    }

    const record = await findActiveUrlByShortCode(normalizedShortCode);

    if (!record) {
        throw new HttpError(404, "Short URL not found");
    }

    addShortCode(normalizedShortCode);

    if (isExpired(record.expiry_at)) {
        throw new HttpError(410, "Short URL has expired");
    }

    const cacheTtlSeconds = getRedisCacheTtlSeconds(record.expiry_at);

    if (cacheTtlSeconds > 0) {
        try {
            await redis.set(cacheKey, record.original_url, "EX", cacheTtlSeconds);
        } catch (error) {
            logger.warn({ err: error, shortCode: normalizedShortCode, cacheKey }, "Redirect cache write failed");
        }
    }

    return {
        originalUrl: record.original_url,
        source: "database"
    };
}

async function warmShortCodeFilter() {
    const shortCodes = await listAllShortCodes();
    initializeShortCodeFilter(shortCodes);
}

module.exports = {
    createShortUrl,
    resolveRedirectTarget,
    warmShortCodeFilter
};